### ISSUE TITLE
Netlify のドメインエイリアスの機能が不安定

### ISSUE THREAD

**Issue by kamataryo** [geolonia/ops#8]
関連: https://github.com/geolonia/e2e/issues/25

Netlify のドメインエイリアスの機能を使って *.tilecloud.io -> *.geolonia.com にリダイレクトされているリソースがいくつかあるが、HTTP リクエストがエラーになっていることがある。
*.tilecloud.io へのリダイレクトが不要ならば、リダイレクトを廃止することで解決できるのが簡単に思われる。

**Comment by kamataryo** [comment]
*.geolonia.com もおかしいことがある。以下は styles.geolonia.com の SSL エラーが出た場合。

```
Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: styles.geolonia.com. is not in the cert's altnames: DNS:*.netlify.com, DNS:netlify.com
    at Object.checkServerIdentity (tls.js:287:12)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1507:27)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket._finishInit (_tls_wrap.js:932:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12) {
  reason: "Host: styles.geolonia.com. is not in the cert's altnames: DNS:*.netlify.com, DNS:netlify.com",
  host: 'styles.geolonia.com',
  cert: {
    subject: [Object: null prototype] {
      C: 'US',
      ST: 'ca',
      L: 'San Francisco',
      O: 'Netlify, Inc',
      CN: '*.netlify.com'
    },
    issuer: [Object: null prototype] {
      C: 'US',
      O: 'DigiCert Inc',
      CN: 'DigiCert SHA2 Secure Server CA'
    },
    subjectaltname: 'DNS:*.netlify.com, DNS:netlify.com',
    infoAccess: [Object: null prototype] {
      'OCSP - URI': [Array],
      'CA Issuers - URI': [Array]
    },
    modulus: 'EC091DCB48D68C6A834C25CFD09962F6E195567AB01D023803427C2F6A2234D4A70F93C559C6F7FB6E4433647D77AC7FB9EF8E63E565C7D040A8299866A15F99DD159997BC25C632DBCEE595A7AB37EFD26C64CD341BE9174332D3C0F579FF2EFCDA1519715697A0EB118CC1E5292C34C90095A470C9C6011DA635473A9EE420B5E42C83FEC8E98A6CA5864A6AC47FDB10E3E456AC41FDBEF47A9B2607524B340A178E955CBD904412B9505D6515E04558C022524E364AEF98672FF0E695458E51DA555138DBFB86D5DCAE75601A4FAE402084FDD5E2BB1A0847BF9A69B8C65452610C574154764B4C5C40AA0A5AED9249CC3627B7D284458F50035C91861DDD',
    bits: 2048,
    exponent: '0x10001',
    pubkey: <Buffer 30 82 01 22 30 0d 06 09 2a 86 48 86 f7 0d 01 01 01 05 00 03 82 01 0f 00 30 82 01 0a 02 82 01 01 00 ec 09 1d cb 48 d6 8c 6a 83 4c 25 cf d0 99 62 f6 e1 ... 244 more bytes>,
    valid_from: 'Jun 15 00:00:00 2020 GMT',
    valid_to: 'Aug  3 12:00:00 2021 GMT',
    fingerprint: 'C1:0F:B1:FB:F1:ED:57:9B:12:29:16:97:B8:49:B8:68:07:2B:9C:65',
    fingerprint256: '8F:FD:A0:46:01:3F:09:2D:B8:E6:53:50:7A:E4:4D:15:3A:67:6D:BF:DD:34:3F:05:F4:4D:14:A8:EC:C5:86:A4',
    ext_key_usage: [ '1.3.6.1.5.5.7.3.1', '1.3.6.1.5.5.7.3.2' ],
    serialNumber: '0B2A4CDA862F17E1649320A3F5B1B0E3',
    raw: <Buffer 30 82 06 23 30 82 05 0b a0 03 02 01 02 02 10 0b 2a 4c da 86 2f 17 e1 64 93 20 a3 f5 b1 b0 e3 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 30 4d 31 0b ... 1525 more bytes>,
    issuerCertificate: {
      subject: [Object: null prototype],
      issuer: [Object: null prototype],
      infoAccess: [Object: null prototype],
      modulus: 'DCAE58904DC1C4301590355B6E3C8215F52C5CBDE3DBFF7143FA642580D4EE18A24DF066D00A736E1198361764AF379DFDFA4184AFC7AF8CFE1A734DCF339790A2968753832BB9A675482D1D56377BDA31321AD7ACAB06F4AA5D4BB74746DD2A93C3902E798080EF13046A143BB59B92BEC207654EFCDAFCFF7AAEDC5C7E55310CE83907A4D7BE2FD30B6AD2B1DF5FFE5774533B3580DDAE8E4498B39F0ED3DAE0D7F46B29AB44A74B58846D924B81C3DA738B129748900445751ADD37319792E8CD540D3BE4C13F395E2EB8F35C7E108E8641008D456647B0A165CEA0AA29094EF397EBE82EAB0F72A7300EFAC7F4FD1477C3A45B2857C2B3F982FDB745589B',
      bits: 2048,
      exponent: '0x10001',
      pubkey: <Buffer 30 82 01 22 30 0d 06 09 2a 86 48 86 f7 0d 01 01 01 05 00 03 82 01 0f 00 30 82 01 0a 02 82 01 01 00 dc ae 58 90 4d c1 c4 30 15 90 35 5b 6e 3c 82 15 f5 ... 244 more bytes>,
      valid_from: 'Mar  8 12:00:00 2013 GMT',
      valid_to: 'Mar  8 12:00:00 2023 GMT',
      fingerprint: '1F:B8:6B:11:68:EC:74:31:54:06:2E:8C:9C:C5:B1:71:A4:B7:CC:B4',
      fingerprint256: '15:4C:43:3C:49:19:29:C5:EF:68:6E:83:8E:32:36:64:A0:0E:6A:0D:82:2C:CC:95:8F:B4:DA:B0:3E:49:A0:8F',
      serialNumber: '01FDA3EB6ECA75C888438B724BCFBC91',
      raw: <Buffer 30 82 04 94 30 82 03 7c a0 03 02 01 02 02 10 01 fd a3 eb 6e ca 75 c8 88 43 8b 72 4b cf bc 91 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 30 61 31 0b ... 1126 more bytes>,
      issuerCertificate: [Object]
    }
  },
  code: 'ERR_TLS_CERT_ALTNAME_INVALID'
}
```
